INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (2, N'Kayak', N'A boat for one person', CAST(275.00 AS Decimal(18, 2)), N'Watersports')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (3, N'Lifejacket', N'Protective and fashionable', CAST(48.95 AS Decimal(18, 2)), N'Watersports')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (4, N'Corner Flags', N'Give your playing field a professional touch', CAST(34.95 AS Decimal(18, 2)), N'Soccer')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (5, N'Stadium', N'Flat-packed 35,000-seat stadium', CAST(79500.00 AS Decimal(18, 2)), N'Soccer')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (7, N'string', N'string', CAST(0.00 AS Decimal(18, 2)), N'string')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (8, N'sdsd', N'sdsdsdsdsdsgggggggggggggggggdsd', CAST(0.00 AS Decimal(18, 2)), N'stsssssring')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category]) 
VALUES (9, N'string', N'string', CAST(0.00 AS Decimal(18, 2)), N'string')
GO